BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: ''
            font_size: 48
            multiline: False
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert m to km'
    Label:
        id: output_label
        font_size: 48
        color: (0, 1, 1, 1)
